---
- name: Installing MySql
  apt:
    name: ['mysql-server', 'mysql-client', 'mysql-common', 'python3-mysqldb']
    state: present
    update_cache: yes
  
- name: create /root/.new.cnf 
  template: 
    src: cnf.j2 
    dest: /root/.new.cnf  
    owner: root 
    mode: 0600


- name: mysql password for root accounts
  mysql_user: 
    name: root host={{ item }} 
    password: "{{ mysql_password }}"
    sql_log_bin: yes
    priv: '*.*:ALL,GRANT'
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - "localhost"

- name: Create a new database with name 'employeedb'
  mysql_db:
    name: employeedb
    state: present

  notify:
    - start_mysql

